### ISSUE TITLE
test automation through continuous integration (CI)

### ISSUE THREAD

**Issue by navidasaman** [navidasaman/FullstackJavaReact#4]
## .github/workflows file should contain:
```
name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Jest Tests
        run: npm test
```

After** jest tests issue has been resolved
